### ISSUE TITLE
Add a bower.json file for Bower

### ISSUE THREAD

**Issue by haydnhkim** [olmokramer/scrollbar-width.js#2]
Hi, I love this repository.
What your opinion about add support for `bower.json` files?

**Comment by olmokramer** [comment]
Hi thanks for the kind words :)
I've never worked with Bower, but I'll take a look at it, probably sometime tomorrow

**Comment by olmokramer** [comment]
JK :P just created bower.json file and registered it. You can now install it with `bower install scrollbar-width.js` etc.

**Comment by olmokramer** [comment]
JK :P just created bower.json file and registered it. You can now install it with `bower install scrollbar-width.js` etc.

**Comment by haydnhkim** [comment]
Great! thanks!
