### ISSUE TITLE
Null is returned

### ISSUE THREAD

**Issue by dy** [olmokramer/scrollbar-width.js#3]
This check https://github.com/olmokramer/scrollbar-width.js/blob/master/scrollbar-width.js#L17 makes function return null in normal budo module run
```js
require('scrollbar-width')() // null
```
This package seems to detect not only scrollbar width, but also if scrollbar is actually present.

**Comment by olmokramer** [comment]
I haven't looked at this code for a few years, but if I remember correctly, that is because while the page is still loading the width of the scrollbar may not be determined correctly yet. You'll have to wait until the document is loaded, e.g.

```js
document.addEventListener('DOMContentLoaded', function() {
    require('scrollbar-width')(); // should report correct width
});
```

**Comment by dy** [comment]
Yep, which makes it useless as direct require, unfortunately :/

**Comment by olmokramer** [comment]
Well, I'm afraid there's nothing I can do about that; it is not possible to get reliable results before the page has finished loading.

**Comment by dy** [comment]
Actually every other scrollbar detector package does that ok - it is enough just to remove that document load check.

Otherwise that is more correctly to call it document-scrollbar-width.
